### ISSUE TITLE
How to make the recurren event on the DB

### ISSUE THREAD

**Issue by Frank004** [mzaragoza/rails-fullcalendar-icecube#3]
Hi very nice example app.
It has everything im looking for. The only thing that I need its that each recurren event to be save to the database or that can be edit.

Im the app im making I have Task and need the recurren of the task.
But on each task recurren I need to have a checkmark completion

**Comment by mzaragoza** [comment]
I don't know if you have seen 
https://github.com/mzaragoza/rails-dhtmlxscheduler 
http://rails-dhtmlxscheduler.herokuapp.com/

I think that this one saves it like you need it

**Comment by Frank004** [comment]
@mzaragoza  Thank  you Ill check it out and let you know

**Comment by Frank004** [comment]
So

**Comment by mzaragoza** [comment]
I am happy to help,  When  needed a calendar I made a couple to figure out what would work best for me.
